language: node_js
node_js:
  - "0.12"

before_script:
  - npm install
  - npm install -g bower
  - npm install -g grunt
  - npm install -g grunt-cli
  - bower install
script: grunt
deploy:
  provider: s3
  access_key_id: $AWS_ACCESS_KEY # declared in Travis repo settings
  secret_access_key: $AWS_SECRET_KEY
  bucket: dev-enrollme-hixme-com
  endpoint: dev-enrollme-hixme-com.s3-website-us-east-1.amazonaws.com
  skip_cleanup: true
  local-dir: dist
  detect_encoding: true
  region: us-east-1
  on:
    branch: develop
notifications:
  email:
    on_failure: always
    on_success: always
