language: node_js
node_js:
  - "0.12"

before_script:
  - npm install
  - npm install -g bower
  - npm install -g grunt
  - npm install -g grunt-cli
  - bower install
script: grunt
deploy:
  provider: s3
  access_key_id: $AWS_ACCESS_KEY # declared in Travis repo settings
  secret_access_key: $AWS_SECRET_KEY
  bucket: enroll-me-dev-hixme-com
  skip_cleanup: true
  local-dir: dist
  acl: public_read
  on:
    branch: develop
notifications:
  email:
    on_failure: always
    on_success: always
